channels:
  - default
  - bioconda
  - conda-forge
dependencies:
  - python
  - jupyter
  - pandas
  - matplotlib
  - scipy
  - statsmodels
  - wquantiles
  - seaborn
  - scikit-learn
  - pygam
  - dmba
  - pydotplus
  - imbalanced-learn
  - prince
  - xgboost
  - graphviz
  - numpy
  - adjustText
  - r-essentials
  - r-base
  - r-vioplot
  - r-corrplot
  - r-gmodels
  - r-matrixstats
  - r-lmperm
  - r-pwr
  - r-fnn
  - r-klar
  - r-dmwr
  - r-xgboost
  - r-ellipse
  - r-mclust
  - r-ca
  - r-ggplot2
  - r-irkernel
  - r-boot
  - r-randomforest
