FROM python:3.10-slim
RUN apt-get update && \
    apt upgrade -y && \
    apt -y install build-essential vim && \
    pip3 install --upgrade pip && \
    mkdir /src
RUN echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
RUN apt install -y curl font-manager git

COPY ./requirements.txt /requirements.txt
RUN pip install --requirement /requirements.txt
