name: build
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true
on: 
  # pull_request: 
  #   paths-ignore:
  #     - '**/*.md'
  push:
    paths-ignore:
      - '**/*.md'    
  workflow_dispatch:
jobs:
  build-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install graphviz
        run: sudo apt install -y graphviz
      - run: pip install --requirement requirements.txt
      - run: cd python/code; python "Chapter 1 - Exploratory Data Analysis.py"
      - run: cd python/code; python "Chapter 2 - Data and sampling distributions.py"
      - run: cd python/code; python "Chapter 3 - Statistical Experiments and Significance Testing.py"
      - run: cd python/code; python "Chapter 4 - Regression and Prediction.py"
      - run: cd python/code; python "Chapter 5 - Classification.py"
      - run: cd python/code; python "Chapter 6 - Statistical Machine Learning.py"
      - run: cd python/code; python "Chapter 7 - Unsupervised Learning.py"
